modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"

[[mixins]]
config = "FarmAndCharm-common.mixins.json"

[[mods]]
modId = "farm_and_charm"
version = "1.2.0"
displayName = "[Let's Do] Farm & Charm"
authors = "satisfy, binaris, jason13"
description = '''
The farm calls: Experience the art of advanced agriculture and farmhouse cuisine! Use mincers, cooking pots, as well as new grains and fruit varieties to enhance your culinary and agricultural skills.
'''
logoFile = "pack.png"

[[dependencies.farm_and_charm]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "doapi"
type = "required"
versionRange = "[1.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "architectury"
type = "required"
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"